server:
  port: 0

spring:
  application:
    name: user-service
  profiles:
    active: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test?autoReconnect=true&rewriteBatchedStatements=true
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.batch_size: 100
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.show_sql: true
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  cloud:
    config:
      name: user-service
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

greeting:
  message: Welcome

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

logging:
  level:
    org.example.userservice.config.feign: debug
    ads.client: debug # open feign package 로그를 보기 위함.
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG

feign:
  retry:
    period: 10
    max-period: 20
    max-attempt: 3